### ISSUE TITLE
Signs will go invisible 

### ISSUE THREAD

**Issue by Bamuel** [Falkirks/MineReset#12] opened 2015-11-10 23:19 UTC
If you place a sign next to the mine tested it for 1-5 blocks away the sign goes invisble

**Comment by Falkirks** [comment] 2015-11-11 05:02
When the mine resets?

**Comment by Bamuel** [comment] 2015-11-13 22:18
yes

**Comment by Falkirks** [comment] 2015-11-14 16:33
This could be a rather hard issue to fix. MineReset serializes the chunks, processes them, and then sets and send them in bulk to the client. If you relog the world, do they reappear?

**Comment by Bamuel** [comment] 2015-11-15 02:07
nope.

But i think its a Pocketmine bug

**Comment by MCPEPIG** [comment] 2016-02-21 06:58
This happens with entities too...

**Comment by Falkirks** [comment] 2016-02-21 15:41
This is due to the fact that the chunks are entirely reset and built from scratch. I don't know if there is currently a way to fix this and be thread-safe.

**Comment by MCPEPIG** [comment] 2016-02-21 17:07
Couldn't you just save the tiles and entities and spawn them back in where
they were?

**Comment by Falkirks** [comment] 2016-02-22 04:36
Yes. This is definitely possible. But would require another management class in the plugin which would require refactoring.

**Comment by Muqsit** [comment] 2016-04-10 13:22
This doesn't happen in v1.0.1
https://github.com/Falkirks/MineReset/releases/download/v1.0.1/MineReset_v1.0.1.phar

**Comment by Falkirks** [comment] 2016-04-10 14:24
@Muqsit That makes sense as that version doesn't work asynchronously.

**Comment by mad-hon** [comment] 2016-06-12 23:02
If it's related to whole chunks being reset, then a suitable workardound would be to find chunk boundaries and making sure any signs are placed in chunks not being modified by mine reset. Right?

**Comment by Falkirks** [comment] 2016-06-13 15:45
@mad-hon I don't understand your point. You could cache all entity data and load it back in, but that would be complicated.

**Comment by mad-hon** [comment] 2016-06-13 21:11
I mean workaround to suggest to users until this issue is resolved.

**Comment by Falkirks** [comment] 2016-06-13 21:23
@mad-hon Oh, I understand, yes

**Comment by anti2canz** [comment] 2016-12-19 12:39
still need a solution :/ signs disappearing

**Comment by mad-hon** [comment] 2016-12-28 23:19
@anti2canz read my workaround above.
The issue is that MineReset overwrites the whole chunk.
So if you place your sings in other chunk than the one you're modifying with MineReset, you'll be fine.
You can learn about chunks at http://minecraft.gamepedia.com/Chunk

**Comment by anti2canz** [comment] 2016-12-29 05:02
@mad-hon oh thanks got it no wonder the disappearing distance varies

**Comment by Falkirks** [comment] 2017-04-17 21:51
I have attempted to add this, but I am getting very strange errors.

**Comment by dktapps** [comment] 2017-04-23 13:45
This issue may be resolved by pmmp/PocketMine-MP@d2efcee115e9edac8c200a9169edfba656ad2c8c .

**Comment by Falkirks** [comment] 2017-04-24 04:57
@dktapps Thanks! I will see what I can do to avoid dropping support for earlier versions.

**Closed** 2017-04-24 16:32 UTC
