### ISSUE TITLE
Disappearing

### ISSUE THREAD

**Issue by InstaGamer** [Falkirks/MineReset#18] opened 2016-03-12 12:48 UTC
I have found a bug in which were you reset a mine all nearby signs or sometimes all signs in the world where you reset the mine will disappear and when a player is in the mine and you reset it the player will become invisible and Sometimes when i use the command /mine reset mine1 the plugin will be disabled in the server for the plugin work again i need to restart the server.. Please fix this bug. LEET need it to be fix and other servers too.

**Comment by Falkirks** [comment] 2016-03-12 15:11
This is a duplicate of #12 and you have provided no details on the plugin being disabled.

**Closed by Falkirks** 2016-03-12 15:11 UTC

**Comment by InstaGamer** [comment] 2016-03-12 15:38
Why do signs disappear when we rest the mines?

**Comment by Falkirks** [comment] 2016-03-12 18:57
Because chunks are created from scratch and thus lose their entities. This was explained in #12
