### ISSUE TITLE
Issue upon mine reset

### ISSUE THREAD

**Issue by randoman911** [Falkirks/MineReset#98] opened 2018-01-31 21:47 UTC
31.01 16:45:29 [Server] Asynchronous Worker #7 thread/CRITICAL ErrorException: "A non-numeric value encountered" (EXCEPTION) in "MineReset_v3.phar/src/falkirks/minereset/task/ResetTask" at line 114
31.01 16:45:29 [Server] Asynchronous Worker #7 thread/DEBUG #0 MineReset_v3.phar/src/falkirks/minereset/task/ResetTask(114): pocketmine\error_handler(integer 2, string A non-numeric value encountered, string phar:///plugins/MineReset_v3.phar/src/falkirks/minereset/task/ResetTask.php, integer 114, array Array())
31.01 16:45:29 [Server] Asynchronous Worker #7 thread/DEBUG #1 src/pocketmine/scheduler/AsyncTask(67): falkirks\minereset\task\ResetTask->onRun()
31.01 16:45:29 [Server] Asynchronous Worker #7 thread/DEBUG #2 (): pocketmine\scheduler\AsyncTask->run()
31.01 16:45:29 [Server] Server thread/CRITICAL Could not execute asynchronous task ResetTask: Task crashed

THIS IS THE WHOLE ERROR PLEASE HELP

**Comment by Falkirks** [comment] 2018-02-01 07:37
This is a duplicate of #97

**Closed by Falkirks** 2018-02-01 07:37 UTC
