### ISSUE TITLE
Mine-reset disabled by a error

### ISSUE THREAD

**Issue by Jorti1** [Falkirks/MineReset#15] opened 2016-01-28 00:07 UTC
Running 0.13.1      Dev 1266

Server] [23:16:08] [Server thread/NOTICE]: InvalidArgumentException: "Argument 4 passed to minereset\Mine::__construct() must be an instance of pocketmine\level\Level, null given, called in phar:///storage/emulated/0/PocketMine/plugins/plugin-214.phar/src/minereset/MineReset.php on line 182 and defined" (E_RECOVERABLE_ERROR) in "/plugin-214.phar/src/minereset/Mine" at line 13
[Server] [23:16:08] [Server thread/INFO]: Disabling MineReset v2.1

My plugins installed

>plugins
[Server] [00:05:03] [Server thread/INFO]: Plugins (48): SimpleAuth v1.7.1, ManyWorlds v2.0.3, WorldEditArt v1.0.0_beta_dev_#048, SignStatus v3.0.0, VIPSlots v0.0.4, AlwaysSpawn v2.2.2, EmptyWorld v1.0.0, NoExplode v1, Slapper v1.2.9, HealthStats v1.1.1, ChestLocker v1.2, Alias v1.2.0, iControlU v1.3, ServerLoveMCPE v3.2, CrateKeys v1.0.5, ItemCloud v1.3, EconomyAPI v2.0.9, EconomyAuction v2.0.2, EconomyCasino v2.0.2, EconomyJob v2.0.4, EconomyLand v2.0.9, EconomyProperty v2.0.6, EconomyPShop v2.0.2, EconomySell v2.0.7, EconomyShop v2.0.7, EconomyTax v2.0.3, EconomyUsury v1.0.1, ItemCasePE v1.0.8, FactionsPro v1.3.2, DevTools v1.10.0, EconomyPotionDispenser v0.0.2, MSpawns v1.5, 1vs1 v0.0.5, Broadcaster v1.16, AdvertisingKick v1.0.0, ChatFilter v1.1, SignShop v2.0.0build3, AutoInv v1.0.1, Farms v1.0-non-alpha, HelpOp v1.0.4, CustomRanks v1.0.0, MineReset v2.1, SimpleAuthHelper v2.0.4, EconomyAirport v2.0.4, VanishNP v1.0.0, RankUp v0.3.1, PurePerms v1.3.0-INDEV, BigBrother v1.5.0-beta

**Comment by Dog2puppy** [comment] 2016-06-17 14:32
Duplicate of #2 and #21

**Comment by Falkirks** [comment] 2016-06-17 22:28
@Dog2puppy is correct.

**Closed by Falkirks** 2016-06-17 22:28 UTC
